# Generated by Django 4.1.1 on 2022-09-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
